# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh" 

plugins=(
	git
	zsh-syntax-highlighting
	zsh-autosuggestions
	docker
	kubectl
)


ZSH_THEME="robbyrussell"

alias catt="/bin/cat"
alias cat="batcat"
alias ip='ip --color=auto'
alias k="kubectl"

# Golang environment
export GOROOT=/usr/local/go
export GOPATH="$HOME/go_projects"
export GOBIN="$GOPATH/bin"
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOBIN

# for install with pip (like ansible)
export PATH=$PATH:/home/totoro/.local/bin

# Have less display colours
# from: https://wiki.archlinux.org/index.php/Color_output_in_console#man
export LESS_TERMCAP_mb=$'\e[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;33m'     # begin blink
export LESS_TERMCAP_so=$'\e[01;44;37m' # begin reverse video
export LESS_TERMCAP_us=$'\e[01;37m'    # begin underline
export LESS_TERMCAP_me=$'\e[0m'        # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'        # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'        # reset underline
export GROFF_NO_SGR=1                  # for konsole and gnome-terminal

# start tmux when open zsh
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  exec tmux
fi

source $ZSH/oh-my-zsh.sh

# >>>> Vagrant command completion (start)
fpath=(/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/contrib/zsh $fpath)
compinit
# <<<<  Vagrant command completion (end)
